# Netlify Configuration for MeetNote Frontend

[build]
  command = "bun run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://meetnote-backend.onrender.com"
