# Netlify Configuration for MeetNote Frontend
# Note: Set "Base directory" to "frontend" in Netlify dashboard

[build]
  command = "npm install && npm run build"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://meetnote-backend.onrender.com"
  NODE_VERSION = "20"
