#!/bin/bash

# This script will NOT work because Render requires manual env var setup
# for security reasons. You MUST use the dashboard.

echo "❌ THIS SCRIPT CANNOT ADD API KEYS AUTOMATICALLY"
echo ""
echo "Render requires you to manually add environment variables through"
echo "the dashboard for security reasons."
echo ""
echo "📋 INSTRUCTIONS:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click on: meetnote-backend"
echo "3. Click on: Environment (left sidebar)"
echo "4. Click on: Add Environment Variable"
echo "5. Enter:"
echo "     Key:   ASSEMBLYAI_API_KEY"
echo "     Value: 598c0c5952444246ba2c1af3eb010d0b"
echo "6. Click: Save Changes"
echo "7. Wait 2-3 minutes for redeploy"
echo ""
echo "🔍 HOW TO VERIFY:"
echo "After redeploy, check logs. You should see:"
echo "  ✅ AssemblyAI configured"
echo ""
echo "NOT:"
echo "  ⚠️  No ASSEMBLYAI_API_KEY found - using mock transcription"
echo ""
echo "🧪 HOW TO TEST:"
echo "Run this command to test if it's working:"
echo ""
echo "curl -X POST https://meetnote-backend.onrender.com/api/meetings/transcribe \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"audio_data\":\"dGVzdA==\",\"format\":\"webm\"}'"
echo ""
echo "If you see the SAME mock text every time, it's not working."
echo "If you see REAL transcription, it's working!"
