# DigitalOcean App Platform Configuration
# Production setup for $200 credits - Full Whisper AI support
name: meetnote-production
services:
- name: api
  source_dir: /backend
  github:
    repo: AbhiCherupally/MeetNote
    branch: main
  dockerfile_path: Dockerfile.production
  instance_count: 1
  instance_size_slug: professional-xs  # 1GB RAM, 1 vCPU - $12/month
  
  # Health check
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Environment variables
  envs:
  - key: ENVIRONMENT
    value: production
  - key: DEBUG
    value: "false"
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
    # Generate with: openssl rand -hex 32
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
    # Will be provided by managed database connection string
  - key: OPENROUTER_API_KEY
    scope: RUN_TIME
    type: SECRET
    # Your OpenRouter API key for AI summaries
  - key: WHISPER_MODEL
    value: base
  - key: WHISPER_DEVICE
    value: cpu
  - key: WHISPER_COMPUTE_TYPE
    value: int8
  - key: CORS_ORIGINS
    value: "https://meetnoteapp.netlify.app,https://meetnote-app.netlify.app,http://localhost:3000,chrome-extension://*"
  - key: DO_SPACES_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DO_SPACES_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: DO_SPACES_BUCKET
    value: meetnote-storage
  - key: DO_SPACES_REGION
    value: nyc3

# Optional: Static site for frontend (if you want to host it on DO too)
# static_sites:
# - name: frontend
#   source_dir: /frontend
#   github:
#     repo: AbhiCherupally/MeetNote
#     branch: main
#   build_command: npm run build
#   output_dir: /out
