# DigitalOcean App Platform Configuration
# Optimized for 512MB RAM Basic Plan ($5/month)
name: meetnote-backend
services:
- name: api
  source_dir: /backend
  github:
    repo: AbhiCherupally/MeetNote
    branch: main
  run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs  # 512MB RAM, 1 vCPU - $5/month
  
  # Health check
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Environment variables
  envs:
  - key: ENVIRONMENT
    value: production
  - key: CORS_ORIGINS
    value: http://localhost:5173,http://localhost:3000,https://meetnoteapp.netlify.app
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: SUPABASE_KEY
    scope: RUN_TIME
    type: SECRET

# Optional: Static site for frontend (if you want to host it on DO too)
# static_sites:
# - name: frontend
#   source_dir: /frontend
#   github:
#     repo: AbhiCherupally/MeetNote
#     branch: main
#   build_command: npm run build
#   output_dir: /out
